### ISSUE TITLE
Resource Id conflicts

### ISSUE THREAD

**Issue by simenkid** [IPSO-Alliance/pub#1]
Hello, I found that Resource id of 5853 conflicts in between Object 3306 (Actuation) and Object 3342 (On/off switch)

* 3306.xml
![3306](https://cloud.githubusercontent.com/assets/7709608/16606892/915a43d2-436e-11e6-9fa7-d681abc5f851.jpg)

* 3342.xml
![3342](https://cloud.githubusercontent.com/assets/7709608/16606897/97c6dcbc-436e-11e6-9287-1925aa400073.jpg)

**Comment by jaimejim** [comment]
I will fix it and also make a registry of Resource IDs too (at some point). Good catch @simenkid thanks again and sorry for the late response.

**Comment by simenkid** [comment]
Thank you Jaime! :+1:

**Comment by jaimejim** [comment]
I have fixed this typo and few others. Also there were some inconsistencies on some resources, I fixed those and added the Reource IDs to the [README ](https://github.com/IPSO-Alliance/pub/tree/master/reg).

Thanks  #again @simenkid and @boaks, I will thus close #1 and #2
