### ISSUE TITLE
3342/5501, wrong name 

### ISSUE THREAD

**Issue by boaks** [IPSO-Alliance/pub#2]
```
<Resources>
<Item ID="5500">
<Name>Digital Input State</Name>
...
<Description>The current state of a digital input.</Description>
</Item>
<Item ID="5501">
<Name>Digital Input State</Name>
...
<Description>The number of times the input transitions from 0 to 1.</Description>
</Item>

```

The content of the element Name (Digital Input State) of Item5501 seems to be a copy paste error.
The IPSO PDF (IPSO-Smart-Objects-Expansion-Pack, 27 October, 2015) contains
Digital Input Counter as resource name.

**Comment by jaimejim** [comment]
Good catch! Now fixed. Thanks!

**Comment by boaks** [comment]
If it's possible for you, can you also trigger this "update" towards the OMA registry (OMNA)?

So they can also correct their definition and close theit issue?
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/116

**Comment by jaimejim** [comment]
Sure thing, already did
