### ISSUE TITLE
3324/5701  

### ISSUE THREAD

**Issue by boaks** [IPSO-Alliance/pub#24]
> <Item ID="5701">
>                 <Name>Sensor Units</Name>
>                 <Operations>R</Operations>
>                 <MultipleInstances>Single</MultipleInstances>
>                 <Mandatory>Optional</Mandatory>
>                 <Type>Float</Type>
>                 <RangeEnumeration></RangeEnumeration>
>                 <Units></Units>
>                 <Description>Measurement Units Definition e.g. “Cel” for Temperature in Celsius</Description>
>             </Item>
> 

Type should be `String`, or?

**Comment by boaks** [comment]
Seems to wrong in many definitions (e.g. 3316).
May be, a general clean up would be not too bad.

**Comment by jaimejim** [comment]
You are correct, sensor units are string. 
Thanks for finding the bug. I will fixit asap.

**Comment by jaimejim** [comment]
It should be fixed now. 
BTW I have been looking for help adding a better validation to travis #22. 
It'd make it easier to catch this type of bugs.
