### ISSUE TITLE
Timestamp as re-usable resource

### ISSUE THREAD

**Issue by hannestschofenig** [IPSO-Alliance/pub#25]
I just noticed that our website at https://github.com/IPSO-Alliance/pub/tree/master/reg says that there is a re-usable resource timestamp, see
 

> Resource	Resource ID	Operations	Type
> Timestamp	5518	R	Time

  
However, when I look at the OMA website at http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html then I don’t see such a resource being registered.
 
Furthermore, when I look at our IPSO Smart Object Packs at https://github.com/IPSO-Alliance/pub/blob/master/docs/IPSO-Smart-Objects.pdf and https://github.com/IPSO-Alliance/pub/blob/master/docs/IPSO-Smart-Objects-Expansion-Pack.pdf then I don’t see it being defined as a re-usable type either (although it is listed as a resource in the GPS Location object).
 
Looks like a bug to me.

**Comment by jaimejim** [comment]
Someone had to register it here:
http://devtoolkit.openmobilealliance.org/OEditor/Register 

I just did, but the process is not very automatic, I don't know if it has been added.

**Comment by hannestschofenig** [comment]
Thanks! There is indeed a human approval processes needed to add new resources and objects (for a good reason).
