### ISSUE TITLE
Review feedback fro the IPSO smart objects specs

### ISSUE THREAD

**Issue by hannestschofenig** [IPSO-Alliance/pub#26]
From: Ben Kinsella [mailto:bkinsella@advantech-bb.com] 
Sent: Thursday, May 18, 2017 10:50 AM
To: support@ipso-alliance.org
Subject: Feedback

I have just started reading some IPSO documentation, and I thought I should let you know that I have come across some typos and some other minor issues.
These are not serious, but they tend to give a bad impression of the overall quality of the platform.

Smart Objects Starter Pack 1.0
•	The “UCUM specification” is mentioned throughout, but it is not listed as a formal reference. Surely it should be?
•	The UCUM spec undergoes changes: http://unitsofmeasure.org/trac/wiki/ChangeLog. Is there any guarantee of forward compatibility?
•	Pages 4,6,7,9,22: missing space: “Description: This IPSO objectis “
•	Page 10: missing space: “Description: This IPSO objectallows”

Smart Objects Expansion Pack
•	Page 2: poor English: “Originally based on OMA LWM2M [1] Object model, IPSO Objects expand the definition it by means of reusable resources.”
•	Pages 6,7: copy-paste error: the text “An example measurement unit is volts” is re-used for Current and Frequency.

OMA LWM2M Object and Resource Registry
•	The text for “Analogue Output” (3203) reads: “This IPSO object is a generic object that can be used with any kind of analogue input interface”. (The text is correct in the IPSO Registry)

Public GitHub
•	Section 6 (Sample Implementations): the link to “JSON file” is broken.

Regards,
Ben.

**Comment by jaimejim** [comment]
Smart Objects Starter Pack 1.0
•	The “UCUM specification” is mentioned throughout, but it is not listed as a formal reference. Surely it should be?
[JJ] Fixed
•	The UCUM spec undergoes changes: http://unitsofmeasure.org/trac/wiki/ChangeLog. Is there any guarantee of forward compatibility?
[JJ] No guarantees unless reported on the issue tracker.
•	Pages 4,6,7,9,22: missing space: “Description: This IPSO objectis “
[JJ] Couldn't find that typo.
•	Page 10: missing space: “Description: This IPSO objectallows”
[JJ] Couldn't find that typo.

Smart Objects Expansion Pack
•	Page 2: poor English: “Originally based on OMA LWM2M [1] Object model, IPSO Objects expand the definition it by means of reusable resources.”
[JJ] Fixed
•	Pages 6,7: copy-paste error: the text “An example measurement unit is volts” is re-used for Current and Frequency.
[JJ] Fixed

OMA LWM2M Object and Resource Registry
•	The text for “Analogue Output” (3203) reads: “This IPSO object is a generic object that can be used with any kind of analogue input interface”. (The text is correct in the IPSO Registry)
[JJ] Fixed

Public GitHub
•	Section 6 (Sample Implementations): the link to “JSON file” is broken.
[JJ] Fixed
