### ISSUE TITLE
Should Checksum be added ? Would it be useful against Bitmap or objects ?

### ISSUE THREAD

**Issue by thadguidry** [IPSO-Alliance/pub#32]
In Wikidata the property checksum https://www.wikidata.org/wiki/Property:P4092 is now available.

This holds the concept of "small-sized datum derived from a block of digital data for the purpose of detecting errors."  And it can use a qualifier property to indicate HOW it is calculated, such as MD5, SHA-512, etc.  https://www.wikidata.org/wiki/Property:P459

Looking at the newly proposed IPSO object "Bitmap" ... I have a hunch that a Checksum might also be needed to support the idea of "detecting errors" in a Bitmap.  The Datatype of Checksum would of course be a String.

Thoughts ?

**Comment by akeranen** [comment]
I think that in case of IPSO SOs checksums would be handled in lower layers during transport or at application (for data at rest). As such I don't see obvious use case for this.

**Comment by thadguidry** [comment]
@akeranen Your probably right.  Certainly a checksum is needed for firmware handling of devices and platforms, but that is covered already (or will be) with some of the Web of Things work.  Lets close this for now
