### ISSUE TITLE
Keeping in sync IPSO Objects with Objects already registered with OMA (OMNA)

### ISSUE THREAD

**Issue by jpradocueva** [IPSO-Alliance/pub#34]
Please note that OMA has been notified that some IPSO objects - registered with OMNA (OMA Name Authority) - are not aligned with the same objects defined in this repository.

Also, please be aware that the LwM2M TS indicates that changes to the resources properties may imply the creation of a new Object version.

We need to establish a coordination between IPSO and OMA to ensure that objects and resources defined in this repository are aligned with the same objects registered in OMNA.

**Comment by jaimejim** [comment]
This is an organizational issue, that has to do with the OMNA Registry and with the evolution of the data model itself.
It is not related to the XML or to this repo in particular.
.
