### ISSUE TITLE
Should Serial Number (aka resource 2) be added to all objects ?

### ISSUE THREAD

**Issue by nvandamme** [IPSO-Alliance/pub#36]
Adding a unique, non mandatory, Serial Number (as resource ID 2) to IPSO objects by default could provide a way to identify each object instances and avoid relying on the object instance ID as it's not order guaranteed.

Use Case:
- Tracking several hardware/software components during their lifetime
- Associate hardware/software uuids with their IPSO descriptions for complex systems

**Comment by jaimejim** [comment]
the use case you mention makes sense to me, I have a proposed PR to simply add a new Resource called "UUID" and define it as Reusable Resource --> #40
However the ResourceID numbers are sequential, in this case it's temporarily 5913

**Comment by boaks** [comment]
> could provide a way to identify each object instances
> avoid relying on the object instance ID as it's not order guaranteed.

I'm not sure, if such a "identify each object instances" as "resource" is useful for REST, where the identity seems to be part of the URI. 
So, should, using the same URI (e.g. "/3201/10") used for the same "endpoint" result in the same "/3201/10/5913" value (e.g. 10.4)? Are different instances then mapped also to different instance ids ("/3201/12/5913" for 10.5)? 

FMPOV, introducing a new "identity candidate" should specify the relation to the already existing ones.

> avoid relying on the object instance ID as it's not order guaranteed.

This seems to imply, that such a order is guaranteed for resource UUID 5913. Is that intended? Where is that specified? 
The object instance id is a `16bit unsigned int`, so the type itself is just ordered as the `float` type of this "5913" resource. 
So where is that "order guarantee" defined?

**Comment by nvandamme** [comment]
Fair point, i should have said unique instead of order guaranteed. In this case an UUID seems the way to go.

**Comment by boaks** [comment]
The object instance is also unique, of course! They have even their definition of uniqness: they are unique within a object. 
So could please specify, what you mean by unique?
And, can you please provide examples, which shows the advantage of the UUID in comparison to the coap://endpoint/oid/iid schema?

**Comment by jaimejim** [comment]
Please note that in my comment I sugggest adding UUID as a resource type not as identifier. 

For REST systems URI's are the way to identify hosted resources. 
On non-REST they might want to use UUID or other. Either way a UUID Resource wasn't in the registry and it seems useful.

**Comment by nvandamme** [comment]
Hi, basically we're already using a specific UUID resource holding hardware UUID for our needs.
This way we can identifiy uniquely each hardware components connected to a device (via readonly EEPROM IC or hardware serial number embeded on each component).
With this in place, we can track our sensors and actuators usage and life cycle.

It is not directly related to the current coap://endpoint/oid/iid schema.

**Comment by boaks** [comment]
Thanks, that makes sense.
