### ISSUE TITLE
Proposed Objects for Lighting and Control

### ISSUE THREAD

**Issue by mjkoster** [IPSO-Alliance/pub#38]
Please see the PR
https://github.com/IPSO-Alliance/pub/pull/37

A proposed set of lighting and control objects that also enable secure peer-to-peer and group communication, scenes, linking, and batch interaction models.

These were developed in 2015 as an extension to the IPSO Smart Object Guideline

**Comment by mjkoster** [comment]
Here are some slides to explain some of the design patterns implemented by the proposed objects.
https://github.com/mjkoster/lighting-objects/blob/master/IPSO-Lighting-Objects.pdf

**Comment by thadguidry** [comment]
I'm wondering how well these patterns fit against the domains of Stage and Architectural lighting...how far can Scenes be linked against groups or arrays that can drive video-pixel mapping systems ?  https://www.etcconnect.com/Products/Architectural-Systems/Mosaic/Designer-2-Software/Features.aspx

**Comment by mjkoster** [comment]
The scope of this proposal is mapping a commonly used model for the controls and affordances of luminaries used in homes, buildings, work places, etc., to IPSO Smart Objects. 

Scenes are meant to be similar to existing design patterns for the simple orchestration of light intensity, color, sound volume, and other simple quantities. 

There is no modeling of light direction, light position, or lighting subjects, nor is there any modeling of movement of position, direction, or subjects in 3 dimensional space, nor is there any modeling of pixel arrays. These things aren't present in the models that are being mapped from.

**Comment by thadguidry** [comment]
Thanks @mjkoster

**Comment by jaimejim** [comment]
Hi @mjkoster and @thadguidry. I have reviewed the PR and looks OK to me, I have added @jpradocueva to review so that OMA is OK with it too. Remember to update the Object list and Resource list. Eventually this should be generated automatically.
