### ISSUE TITLE
UUID Resources

### ISSUE THREAD

**Issue by nvandamme** [IPSO-Alliance/pub#42]
Hi,

The new proposed resource type UUID (5913) is registered as float.
For complex UUIDs (derived from SHA*, EC or RSA) maybe the type string should be better suited ?

Also, there is already an IPSO resource for serial numbers typed as string (2), maybe using this resource as is should be better ?

But, for resource type 2, it seems that some core object models (1, 2, 4, 5, 6, 7 and 12)  does not using type 2 resource as a serial number resource, implying that these objects are exceptions to the general LwM2M specs...

**Comment by JanneKiiskila** [comment]
Fully agree with @nvandamme  - UUID can't be a float. 

https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by jaimejim** [comment]
As UUID is not used in any of the current registered objects and it aligns better with OMA spec. I just added a fix in #49.
