### ISSUE TITLE
What happens when an object ID in range 26241-32768 is reused by different vendors?

### ISSUE THREAD

**Issue by valensd-etc** [IPSO-Alliance/pub#51]
Hi,

I'm new to IPSO smart objects but I am looking to use it in new development. I read the OMA guidelines for Smart Objects [http://www.openmobilealliance.org/documents/whitepapers/OMA-ORG-Guidelines_Creation_Registration_LwM2M_Objects_Resources-V1_0-20180209-A.pdf](url)

In Section 7.2.1 it shows Object Ids in range 26241 to 32768 can be reused by vendors without registration. What happens when 2 different vendors reuse the same Object ID for different purposes (Different resourcses, etc)?

> 26241 – 32768 Objects created by Vendors. Numbers in this
range can be re-used, no registration is
needed

Thanks

**Comment by jpradocueva** [comment]
@valensd-etc this range was created for the vendors. They can create **vendor** related Objects, meaning Objects that are not Global but linked to the vendor environment.
