### ISSUE TITLE
Timestamp of individual sensors

### ISSUE THREAD

**Issue by ky0on** [IPSO-Alliance/pub#54]
I'm using IPSO and LWM2M to manage our sensors.

What is the best way to store the timestamp when a sensor value is measured in sensor objects?
For instance, [temperature object](https://github.com/IPSO-Alliance/pub/blob/master/reg/xml/3303.xml) does not have resources to store the timestamp.

**Comment by jpradocueva** [comment]
@ky0on  please note that this repository "pub" has been marked as private. All the discussion related to old IPSO Objects are taking place in a private repository in OMA. If you want to submit a comment then please use this public repository Issue Tracker: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues
A Working Group inside of OMA called "IPSO" is currently reviewing all the Objects created by IPSO. In due course, you will see an update of the old IPSO objects here in the OMA Registry for LwM2M: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
