### ISSUE TITLE
No AppType in 3303 ?

### ISSUE THREAD

**Issue by daniel-dnil** [IPSO-Alliance/pub#56]
Assuming a device which has multiple instances of the temperature sensor object, ID 3303, each sensor can be uniquely identified by its instance number. But how to convey the mapping between instance number of sensing object to the server, assume for example ID 0 : "Indoor temp" ID 1 : "Outdoor Temp". Many IPSO objects have resource ID 5750, "Application Type" which could convey this massping, but this resource is not present on 3303. Seems related to issue #29 ?

**Comment by jpradocueva** [comment]
@daniel-dnil please note that this repository "pub" has been marked as private. All the discussion related to old IPSO Objects are taking place in a private repository in OMA. If you want to submit a comment then please use this public repository Issue Tracker: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues
A Working Group inside of OMA called "IPSO" is currently reviewing all the Objects created by IPSO. In due course, you will see an update of the old IPSO objects here in the OMA Registry for LwM2M: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
