### ISSUE TITLE
3314 - reason for no min-max range values (5603 - 5604)

### ISSUE THREAD

**Issue by boaks** [IPSO-Alliance/pub#6]
Is there a reason, why 3313 (accelerometer) has min-max range value (5603, 5604), 
but 3314 (magnetometer) hasn't?

**Comment by jaimejim** [comment]
When we wrote the objects we didn't have a good example for that one. So we didn't add the range. 
However, since they are both Optional Resources, you can add min-max, it should not be a problem.
If this is an issue we can update that particular Object.

**Comment by boaks** [comment]
> However, since they are both Optional Resources, you can add min-max, it should not be a problem.

Is your intention, that I can add that resource to the object definition?
Or that there is no need to explicitly list a optional reusable resource at the object definition?

**Comment by boaks** [comment]
With the clarification of the OMA, all resources must be defined explicitly in the object definition.

> If this is an issue we can update that particular Object.

After the clarification, FMPOV it is an issue.

**Comment by jaimejim** [comment]
I'll close this issue as it is now being tracked here:
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/205
